spring:
  application:
    name: swiggy-restaurant
  profiles:
    active: dev2
    # THIS activates
server:
  port: 5016

---

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:swiggy_restaurants
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: dev2
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:orcl
    username: system
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  properties:
#    hibernate:
#      dialect:
