spring:
  application:
    name: swiggy-user-service
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url:
    password:
    username:
    driver-class-name: org.h2.Driver
server:
  port: 5017